# Generated by Django 3.0.8 on 2020-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtimetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='column_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
