# Generated by Django 3.0.8 on 2020-07-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createtimetable', '0003_auto_20200728_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnname',
            name='row_name',
        ),
    ]
