# Generated by Django 3.0.8 on 2020-07-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtimetable', '0005_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='item',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='column_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='createtimetable.columnName'),
        ),
    ]
