# Generated by Django 3.0.8 on 2020-07-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createtimetable', '0006_auto_20200729_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnname',
            old_name='column_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rowname',
            old_name='row_name',
            new_name='name',
        ),
    ]
